/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package AVSim-0.1.0.0 */
#ifndef VERSION_AVSim
#define VERSION_AVSim "0.1.0.0"
#endif /* VERSION_AVSim */
#ifndef MIN_VERSION_AVSim
#define MIN_VERSION_AVSim(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_AVSim */

/* package base-4.13.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.13.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  13 || \
  (major1) == 4 && (major2) == 13 && (minor) <= 0)
#endif /* MIN_VERSION_base */

/* package containers-0.6.2.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.2.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 2)
#endif /* MIN_VERSION_containers */

/* package directory-1.3.6.0 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.6.0"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_directory */

/* package filepath-1.4.2.1 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.1"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */

/* package safe-0.3.19 */
#ifndef VERSION_safe
#define VERSION_safe "0.3.19"
#endif /* VERSION_safe */
#ifndef MIN_VERSION_safe
#define MIN_VERSION_safe(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 19)
#endif /* MIN_VERSION_safe */

/* package threepenny-gui-0.9.0.0 */
#ifndef VERSION_threepenny_gui
#define VERSION_threepenny_gui "0.9.0.0"
#endif /* VERSION_threepenny_gui */
#ifndef MIN_VERSION_threepenny_gui
#define MIN_VERSION_threepenny_gui(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_threepenny_gui */

/* package time-1.9.3 */
#ifndef VERSION_time
#define VERSION_time "1.9.3"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 3)
#endif /* MIN_VERSION_time */

/* tool gcc-9 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "9"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  0 || \
  (major1) == 9 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.8.4 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.8.4"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  8 || \
  (major1) == 8 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.8.4 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.8.4"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  8 || \
  (major1) == 8 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.23.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.23.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  23 || \
  (major1) == 2 && (major2) == 23 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool runghc-8.8.4 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.8.4"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  8 || \
  (major1) == 8 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.34 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.34"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  34 || \
  (major1) == 2 && (major2) == 34 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "AVSim-0.1.0.0-K6unqWxNGerDZ7felrILif-AVSim"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
